dist: xenial
install:
- sudo rm -vf /etc/apt/sources.list.d/*
- sudo apt-get update
- mispipe "mv ~/.nvm ~/.travis-nvm-disabled" ts
- mispipe "pip install codecov" ts || mispipe "pip install codecov" ts
- mispipe "tools/ci/setup-$TEST_SUITE" ts
- mispipe "scripts/lib/clean-unused-caches --verbose --threshold 0" ts
cache:
  yarn: true
  apt: false
  directories:
  - "$HOME/zulip-venv-cache"
  - "$HOME/zulip-npm-cache"
  - "$HOME/zulip-emoji-cache"
  - "$HOME/node"
  - "$HOME/misc"
env:
  global:
  - BOTO_CONFIG=/nonexistent
language: python
matrix:
  include:
  - python: '3.5'
    env: TEST_SUITE=production
sudo: required
addons:
  artifacts:
    paths:
    - $(ls var/casper/* | tr "\n" ":")
    - $(ls /tmp/zulip-test-event-log/* | tr "\n" ":")
  postgresql: '9.5'
  apt:
    packages:
    - moreutils
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_2a68b6131c57_key -iv $encrypted_2a68b6131c57_iv
  -in root_key.enc -out root_key -d
